name: CI
on:
    release:
        types: [published]
    push:
        branches: [master]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Add SSH key
              env:
                  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
              run: |
                  mkdir -p /home/runner/.ssh
                  ssh-keyscan -p 2222 -t rsa anvil.works >> /home/runner/.ssh/known_hosts
                  echo "${{ secrets.ANVIL_SSH_KEY }}" > /home/runner/.ssh/github_actions
                  chmod 600 /home/runner/.ssh/github_actions
                  ssh-agent -a $SSH_AUTH_SOCK > /dev/null   
                  ssh-add /home/runner/.ssh/github_actions
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "james.campbell@tanti.org.uk"
                  git remote add anvil ssh://james.campbell%40tanti.org.uk@anvil.works:2222/DUZISAHMZQMOO53Q.git
                  git push anvil master -v